# Generated by Django 5.0.6 on 2024-07-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contact_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='password',
        ),
    ]
